#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oset
Version  : 0.1.3
Release  : 6
URL      : https://files.pythonhosted.org/packages/d6/b1/a49498c699a3fda5d635cc1fa222ffc686ea3b5d04b84a3166c4cab0c57b/oset-0.1.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/d6/b1/a49498c699a3fda5d635cc1fa222ffc686ea3b5d04b84a3166c4cab0c57b/oset-0.1.3.tar.gz
Summary  : Ordered Set.
Group    : Development/Tools
License  : Python-2.0
Requires: oset-python = %{version}-%{release}
Requires: oset-python3 = %{version}-%{release}
Requires: setuptools
BuildRequires : buildreq-distutils3
BuildRequires : setuptools

%description
=====
        
        Set that remembers original insertion order.
        
        Runs on Py2.5 or later (and runs on 3.0 or later without any modifications). For Python2.5, a local backport of ABC classes is also used.
        
        Implementation based on a doubly linked link and an internal dictionary. This design gives OrderedSet the same big-Oh running times as regular sets including O(1) adds, removes, and lookups as well as O(n) iteration.
        
        Usage
        -----
        
        Import and create ordered set.

%package python
Summary: python components for the oset package.
Group: Default
Requires: oset-python3 = %{version}-%{release}

%description python
python components for the oset package.


%package python3
Summary: python3 components for the oset package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oset package.


%prep
%setup -q -n oset-0.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545677928
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
